site_name: Ming Coding Patterns

nav:
    - Introduction: index.md
    - Dash Patterns: dash.md
    - Python: python.md
    - Git: git.md
theme:
    name: material

plugins:
    - search
    - git-authors:
        show_contribution: true
    - git-revision-date-localized:
        type: datetime

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
            